### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by steev** [linuxdeepin/deepin-metacity#2]
When compiling with a 6.4.0 compiler, I get the following two warnings:

` QA Notice: Package triggers severe warnings which indicate that it may exhibit random runtime failures.

 core/screen.c:3218:7: warning: incompatible implicit declaration of built-in function ‘abort’
 core/deepin-dbus-service.c:198:5: warning: incompatible implicit declaration of built-in function ‘free’`

These are both covered by adding a

#include <stdlib.h> to the above files.

**Comment by sonald** [comment]
fixed
