### ISSUE TITLE
Build fails on new YELP_HELP_RULES

### ISSUE THREAD

**Issue by W-Floyd** [linuxdeepin/deepin-metacity#3]
yelp-tools seems to have deprecated YELP_HELP_RULES, and [metacity has also removed it at some point.](https://git.gnome.org/browse/metacity/commit/?id=8c7aebb4a08f2589a94a314c105e7aa841c51621).

I have tentatively created a similar patch that allows the build to complete. Should I PR that?

**Comment by sonald** [comment]
@W-Floyd would it be possible if you can send a PR to https://cr.deepin.io, we can not accept github PR right now.

**Comment by W-Floyd** [comment]
Sure, I'll have a look at it soon.

**Comment by W-Floyd** [comment]
Sorry for the delay, I have submitted a PR now.

**Comment by sonald** [comment]
thanks
